// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_lEbmkRCKH7p-mfcZ-WiO6wQRydVFZn8',
    appId: '1:737399152771:web:e7261713103546cd1e3bb6',
    messagingSenderId: '737399152771',
    projectId: 'chamawise-1ef86',
    authDomain: 'chamawise-1ef86.firebaseapp.com',
    storageBucket: 'chamawise-1ef86.firebasestorage.app',
    measurementId: 'G-PTS8R5NHPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7uWWoNlYVNz5xjR1N1bqwLdALf_S1Fx4',
    appId: '1:737399152771:android:eb23dc2396970ad41e3bb6',
    messagingSenderId: '737399152771',
    projectId: 'chamawise-1ef86',
    storageBucket: 'chamawise-1ef86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGJ8SRCudO26GHKNB3wEItP2tjLKHfZ4',
    appId: '1:737399152771:ios:6e1726afcdc667681e3bb6',
    messagingSenderId: '737399152771',
    projectId: 'chamawise-1ef86',
    storageBucket: 'chamawise-1ef86.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_lEbmkRCKH7p-mfcZ-WiO6wQRydVFZn8',
    appId: '1:737399152771:web:aec4902bdf782fb41e3bb6',
    messagingSenderId: '737399152771',
    projectId: 'chamawise-1ef86',
    authDomain: 'chamawise-1ef86.firebaseapp.com',
    storageBucket: 'chamawise-1ef86.firebasestorage.app',
    measurementId: 'G-MQ4FB8G4EC',
  );
}
